### PR TITLE
added shows to database

### PR DESCRIPTION
**Pull request by will-hedges**
merged previous PRs, added shows

### CODE REVIEW

**Review by ristopherCh — CHANGES_REQUESTED** [review]
WRONG! Missing bracket.

**Review by loganallengray — CHANGES_REQUESTED** [review]
Missing bracket on line 92-93

**Comment by will-hedges** [comment]
OK I GET IT I'LL FIX IT

**Review by yerwhile — APPROVED** [review]
I don't see any missing brackets. I see no evil.

**Review by loganallengray — APPROVED** [review]
👍

**Review by ristopherCh — APPROVED** [review]
You have now met my incredibly high standards.

**Pull request merged**
