### PR TITLE
actors database

### PR DESCRIPTION
**Pull request by yerwhile**
actors database and actor getter

### CODE REVIEW

**Review by ristopherCh — APPROVED** [review]
That Chevrolette McAdoo is a superstar.

**Review by loganallengray — CHANGES_REQUESTED** [review]
Please format code.

**Review by will-hedges — CHANGES_REQUESTED** [review]
I think we need fewer than 10 actors, so that we can show the same actor in multiple shows

**Comment by yerwhile** [comment]
> I think we need fewer than 10 actors, so that we can show the same actor in multiple shows

How many 7?

**Comment by ristopherCh** [comment]
> Please format code.

very strict, Logan.

**Review by will-hedges — APPROVED** [review]

**Pull request merged**
