### PR TITLE
Cjh modules

### PR DESCRIPTION
**Pull request by ristopherCh**
Added actors.js, genres.js, and shows.js modules.

I really hope you enjoy my changes.

### CODE REVIEW

**Review by loganallengray — APPROVED** [review]
👍

**Review by yerwhile — APPROVED** [review]
These changes were more enjoyable than most. I would give these changes 9/10.

**Review by will-hedges — APPROVED** [review]
Looks great. Thanks Chris!

**Review by Valerie-Freeman — COMMENTED** [review]
Looks great!

**Pull request merged**
